// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vNnwQiPSuShx-CbdIAL7d_c32Vq-57o',
    appId: '1:576473164584:web:cc6cec22b6f0e474d3be1d',
    messagingSenderId: '576473164584',
    projectId: 'instragram-clone-6a583',
    authDomain: 'instragram-clone-6a583.firebaseapp.com',
    storageBucket: 'instragram-clone-6a583.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNk06jfWK5FhXxc1ZFM1PGRc8sDjcRRA8',
    appId: '1:576473164584:android:e253f7af345906d4d3be1d',
    messagingSenderId: '576473164584',
    projectId: 'instragram-clone-6a583',
    storageBucket: 'instragram-clone-6a583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0nsClKeiuCxvMsvs8JsnjsSlNGi4wKs',
    appId: '1:576473164584:ios:5d83e3a214831cb1d3be1d',
    messagingSenderId: '576473164584',
    projectId: 'instragram-clone-6a583',
    storageBucket: 'instragram-clone-6a583.appspot.com',
    androidClientId: '576473164584-9b0scdvf11ndn9dt2g061384s0ma8rv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
